name: Daily Scraper

on:
  schedule:
    - cron: '0 12 * * *' # 8:00 am EST
  workflow_dispatch: # manual trigger
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        default: ''
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual run with inputs..."
            python USGSScraper.py "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}"
          else
            echo "Scheduled run with default dates..."
            python USGSScraper.py
          fi
